name: on_pr

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened

jobs:
  rubocop:
    uses: ./.github/workflows/rubocop.yml
  rspec:
    needs: rubocop
    uses: /.github/workflows/rspec.yml