name: Rspec

on:
  pull_request:
    branches:
      - main


jobs:
  rspec:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: tch_test
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      RAILS_ENV: test
      DATABASE_URL: postgres://postgres:postgres@localhost/tch_test
      MAP_BOT_ACCESS_TOKEN: ${{ secrets.MAP_BOT_ACCESS_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.4

      - name: Install dependencies
        run: bundle install

      - name: Setup database
        run: |
          bin/rails db:create
          bin/rails db:schema:load

      - name: Run tests
        run: bundle exec rspec

      - name: Create coverage folder
        run: |
          mkdir -p coverage_results
          cp coverage/.resultset.json coverage_results/.resultset.json
      - name: List coverage files
        run: ls -la coverage/

      - name: Upload coverage file
        uses: actions/upload-artifact@v4
        with:
          name: rspec-coverage
          path: coverage_results/.resultset.json

  report-coverage:
    runs-on: ubuntu-latest
    needs: rspec
    steps:
      - name: Download coverage artifact
        uses: actions/download-artifact@v4
        with:
          name: rspec-coverage
          path: coverage_results/

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.4

      - name: Install dependencies
        run: bundle install

      - name: Run coverage report
        run: bundle exec rake db:coverage:report
